### ISSUE TITLE
Design Docs To-Do List

### ISSUE THREAD

**Issue by mwmadsen67** [vuongcindy/Kirara#1]
# Wiki Page Home

- [ ] Is the first page you see upon entering the wiki
- [ ] Contains a welcome message
- [ ] Contains a link/placeholder for a link to the live page
- [ ] All links in the right sidebar should contain each wiki page and link to the correct page
- [ ] Correctly formatted
    - [ ] each wiki page is listed in bullet points
    - [ ] all links route the correct page

---

# MVP List

- [ ] Should have 7 MVPs.
    - [ ] 3 of those are User Auth, Heroku, and Production README.
    - [ ] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [ ] Contains a description sentence of the app
- [ ] Includes two to three detailed bullets on functionality and presentation of feature
- [ ] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [ ] Estimates how long it will take the code each MVP
- [ ] Correctly formatted
    - [ ] MVPs are listed in an ordered list
    - [ ] Each MVP is broken down into bullet points

---

# Database Schema

- [ ] Contains correct datatypes
- [ ] Contains appropriate constraints/details
    - [ ] primary key
    - [ ] not null
    - [ ] unique
    - [ ] indexed
    - [ ] foreign key
- [ ] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - [ ] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [ ] Correctly formatted
    - [ ] schema is written in a table format
    - [ ] the table's name are lowercased, snake_cased and `back_ticked`
    - [ ] the table header column names are bolded
    - [ ] columns names are lowercased and snaked_cased and `back_ticked`

---

# Sample State

- [ ] State shape is flat!
- [ ] State's keys are camelCased
- [ ] All keys within the values in the state are accessible in the schema
- [ ] Correctly formatted
    - [ ] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [ ] Top level slices
        - [ ] `entities`
        - [ ] `session`
        - [ ] `errors` (here or in `ui`)
        - [ ] `ui` (if needed)
    - [ ] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

---

# Backend Routes

- [ ] Contains the following sections: HTML, API Endpoints(Backend)
- [ ] Each route has a description
- [ ] API Endpoint routes contains wildcard variables written in `snake_case`
- [ ] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [ ] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

---

# Frontend Routes

- [ ] Frontend routes contains wildcard variables written in `camelCase`
- [ ] Correctly formatted
    - [ ] Routes are displayed with `inline coding text` (backticks)

**Comment by mwmadsen67** [comment]
Hi Cindy, below are some notes I have on your current design docs:

**MVP List:**
- I think the Movie MVP should be before the category MVP, that way you can work on active storage earlier on and get the main part of your app done first.
- search is a good MVP but the splash page is not it's own MVP, I would work on that as part of your user auth MVP or at the same time as your movie MVP
- for an additional MVP, a watch list feature would probably be best.
- I personally think that having multiple users or profiles is a better MVP than categories, since this project is very light on CRUD features. I might even suggest doing users after user auth and then do movies after. Happy to talk about this further if you'd like.

**Schema:**
- users looks good 👍 
- for videos, Im not sure what that watch_status_id is for, nor am I sure what that table is for.
- you wont need to store any urls in the database, so you wont have a column for thumbnailUrl nor a video url, we will handle that with active storage.
- for genres, rather than having a table containing video ids, you might want your movies to have a genre_id column, or it might be easiest to just have genre be a column in your movies table.
- I'm not sure what the point of the studio table is either, this could also just be a column in movies
- I would add profiles and watch list tables as mentioned above

**Sample State:**
- make sure not to have underscores in your sample state keys
- videos will also end up having videoUrls
- otherwise it looks good, just keep in mind if you end up making the above changes to your schema youll have to update this as well

**Backend Routes:**
- GET /api/users is a user index request, not a request for a specific user. As far as I know, disney plus doesnt have that functionality
- if you made changes I mentioned, most of these would be updated. If you wanted to search for a specific genre of movies, or studio, you can have requests that add a query string to the movie index request, for example: `GET /api/movies?studio=ghibli&genre=horror` 

**Frontend Routes:**
- what is login/password for?
- it looks like some type of a movie show page is missing
- otherwise looks good

**Comment by mwmadsen67** [comment]
Alright nice job on the changes, a couple more notes:

MVP List, Schema, and Sample State, and frontend routes are all complete. 👍 

Backend Routes:
* I dont think you need 2 routes with watching the video, but maybe you have an idea with that that I'm not aware of.
* I also dont think youll need a backend route to get 1 watchlist item
